name: Lint & Code Style

on:
  push:
    branches:
      - main
      - nightly
  pull_request:
    branches:
      - main
      - nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Run Ruff Checks
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."

      - name: Run Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."